* Ética y Renovación
  :PROPERTIES:
  :CUSTOM_ID: ética-y-renovación
  :END:

** Resúmen Corto
   :PROPERTIES:
   :CUSTOM_ID: resúmen-corto
   :END:

Los textos de Kaizo hacen a la propuesta Ética de Husserl, quien piensa
a la Ética desde una posición de *renovación personal y cultural*. Es
necesario, entonces, para él, atacar los dos frentes a la vez, dado que
son, en algún sentido, complementarios:

1. Renovación Personal.
2. Renovación Cultural.

Por lo mismo, la manera en que 1. y 2. se fundamentan reciprocamente es
uno de los temas principales de estos artículos. Husserl entiende la
*renovación* como apuntando como su meta hacia la asunción de la
auto-responsabilidad de las acciones prácticas tanto por parte de los
sujetos empíricos o personalidades humanas, como de los Umwelt o
comunidades. De lo que se trata es de mostrar la posibilidad del nacer o
re-nacer de la persona /auténticamente humana/ y de la /humanitas/ como
humanidad verdadera.

Como ya el propio título de los artículos casi que declára, la propuesta
de Husserl se inscribe dentro de las corrientes éticas *personalistas*
que tendrían su comienzo con Kant. Esto es: se pone énfasis en la
persona y en su racionalidad, a la vez que se la considera
inexorablemente atravesado por la comunidad en la que vive. En última
instancia, el proyecto de Husserl es realizar una *Crítica de la Razón
Práctica*. El fundamento último de la vida ética es la
*responsabilidad*. Solo asumiendonos como seres racionales, responsables
de nuestras acciones prácticas, llegaremos a ser *auténticamente
humanos*.

La responsabilidad implica *tomar conciencia* de que nos
*auto-determinamos*: antes de, en y a través de nuestras acciones
prácticas. Pero tal toma de conciencia no es solo una tarea para el
hombre, sino también para las comunidades de hombres, para los
diferentes /Lebenswelt/ por así decirlo, en sus múltiples dimensiones.
La *vocación* como realización de la responsabilidad es otro punto
central para Husserl, vocación que debemos *amar*. Amor y Asunción de la
Responsabilidad en la elección como auto-determinación son conceptos
centrales del planteamiento husserliano. Así se *concretiza* el
*Imperativo Categórico* de Husserl: se hombre auténtico, o haz lo mejor
teniendo en cuenta el alcance de tus posibilidades racionales. Por ello
el *auto-exámen personal* es tan importante para Husserl. Solo mediante
mediante la auto-conciencia y el auto-exámen como un momento de la
primera, podemos llegar a los ideales regulativos que me guién como
hombre, como profesional, como miembro-enlazado de tales o cuales
comunidades (amistad, pareja, Iglesia, Patria, etc, etc.), y al juicio
sobre lo correcto o incorrecto de mi proceder práctico en tales o cuales
ocasiones.

Dada la centralidad de la auto-responsabilidad, la auto-determinación y
la vocación, Husserl concibe la posibilidad de una ética hasta cierto
punto /pluralista/. Mi responsabilidad está atada a mi vocación. Puedo
admirar otras vocaciones, otros imperativos categóricos, pero no puedo
amarlos, no pueden ser "auténticamente míos". Lo mismo, seguramente,
puede decirse /mutatis mutandis/ de otras formas de vida, de otros
momentos formales que hagan a la unidad de otros /Lebenswelt/.

** Ideas
   :PROPERTIES:
   :CUSTOM_ID: ideas
   :END:

-  No hay un tratamiento explicito de la noción de *prójimo* acá, que en
   el texto de 1923 define como: miembros de una comunidad estrecha
   (Umwelt?).
-  La *actitud personalista* de este texto implica que el individuo
   siempre es el /punto cero/ de toda referencia, lo mismo que el cuerpo
   lo era del espacio. En este sentido Husserl se sentiría (¿se sentía?)
   cerca de Avenarius, por lo que en el texto de 1923 declára: "tiene
   esta comunidad próxima como miembro central (Zentralgleid?) respecto
   de comunidades más abarcadoras que, ellas mismas, pueden ser
   nuevamente miembro central para otras más abarcadoras".
-  El punto anterior queda explicito en el título de esa parte del
   texto: "Representación natural del mundo. El mundo personal y el
   mundo de las cosas en sus orientaciones subjetivas. El ser humano
   como el que valora y el que actúa prácticamente". Esto es
   /Naturlicher Weltbegrif/ en términos de Avenarius [1]

** Introducción (Emiliano)
   :PROPERTIES:
   :CUSTOM_ID: introducción-emiliano
   :END:

Publicados entre 1922/1924, años similares a los textos de /Erste
Philosophie/ (1923/24). El tema de los textos se puede recuperar a
través de una carta:

#+BEGIN_QUOTE
  Mi tema [VIII] se refería al título de la revista Renovación.
  Renovación en el sentido de conversión ética y de configuración de una
  cultura ética universal de la humanidad.
#+END_QUOTE

El contexto, la 1era GM:

#+BEGIN_QUOTE
  Lo que ha puesto al descubierto la guerra es la indescriptible
  miseria, no sólo moral y religiosa, sino filosófica de la humanidad.
#+END_QUOTE

#+BEGIN_QUOTE
  Esta guerra ---escribe en la misma época a Winthrop Bell---, el pecado
  más universal y profundo de la humanidad en toda su historia, ha
  puesto a prueba todas la ideas vigentes en su impotencia e
  inautenticidad... La guerra del presente, convertida en guerra del
  pueblo en el más estricto y horroroso sentido de la palabra, ha
  perdido todo su sentido ético». Por ello, para la «renovación
  ética-política de la humanidad» se hace necesario «un arte de la
  educación universal de la humanidad, que esté sustentado por los más
  altos ideales éticos, claramente fijados; un arte en forma de una
  poderosa organización literaria para ilustrar a la humanidad y
  educarla conduciéndola en el camino de la veracidad.
#+END_QUOTE

Se adelantan, entonces, los temas de /Krisis/. O más bien, el
*diagnóstico* acerca de la perdida del rumbo de Occidente que será el
primer motor o la primera motivación para los análisis que Husserl
emprende en esa obra. El propósito de Husserl es intervenir en una
situación histórica de decadencia, de inautenticidad, a través de la
fenomenología, como ciencia de las esencias, capaz de fijar las metas
propias de la humanidad europea en un momento de crisis moral, cuya
manifestación más poderosa encuentra en la primera guerra mundial.

Husserl piensa, acá, la crisis como una *crisis de los valores*. Del
entramado ideológico que sustenta las relaciones interpersonales y las
metas propias de las sociedades occidentales. Seguramente el
*positivismo* de su época, en sus reververaciones político-morales son,
ya en este momento, para él, el fundamento, o al menos parte del
problema. Pero solo en /Krisis/ atacará al positivismo con todo el rigor
y la fuerza de la fenomenlogía. En /Krisis/, lo que diagnostica ante
todo es una *falta* por así decirlo, pero más bien en el sentido de una
carencia, de una pobreza, de una ausencia, que conlleva, entonces, a una
perdida del rumbo. Rumbo que está dado por una meta, un telos, un
propósito. Veremos que dice acá en los artículos para Kaizo. Pero
recordemos, sin embargo, que la *Ética* vista en Krisis como un momento
/de orden superior/, esto es, como un /estrato fundamentado/, no se
trata o no se tematiza directamente.

Para ocuparnos del tema ético en Husserl deberíamos leer /Lecciones
sobre ética y valores/ (Hua XXVIII), y probablemente también las
lecciones sobre Fichte. El introductor propone tres etapas para
comprender las reflexiones éticas de Husserl.

1. Superación del Escepticismo.

El *escepticismo gnoseológico* o *epistemológico* se refuta en las /LU/.
Pero dicha refutación del escepticismo permanece cerrada en tal esfera
(e incluso, todavía, en la esfera más reducida de la /lógica pura/). Es
cierto que pronto otros autores recojen el guante e intentan superar el
relativismo/escepticismo en otras esferas: Moritz Geiger en la
/estética/, Max Scheller en la /ética/, etc., etc. Husserl también se
aplica a este proyecto, e intentará refutar el psicologismo ético,
asumiendo la posibilidad de hacer *juicios de valor objetivos*. El punto
es que, al /volver a las cosas mismas/ se puede refutar el psicologismo
en la esfera que sea. Este es el "poder" de la fenomenología, o del
método fenomenológico (lejos, devuelta, estamos de la compresión de la
fenomenología como una doctrina que habla de aquello propio de la
/primera persona/). Es en *las cosas mismas* que encontramos la
evidencia para nuestros juicios objetivos, ya sean cognoscitivos o
valorativos. Partimos, siempre, de la manera o la forma en que las cosas
se dan a la conciencia. Pero nuevamente, hay que comprender esto bien:
no de la manera en que se dan /a mí/ conciencia, sino a una /conciencia
trascendentalmente reducida/, capaz de comprender los /horizontes de
sentido relativos/ propios de ella, y capaz por lo mismo de
/cancelarlos/ para dejar que la cosa aparezca con el /brillo/ que le es
propio. Si la fenomenología descansa en la conciencia, no por ello
descansa en /la primera persona/, sino que descansa en la conciencia
como una /lógica trascendental/ a la que llegamos por vía de la
reducción, y que nos permite describir no el mundo para Emiliano, para
Debb, para Matias, para la hermana de Popi; sino /El Mundo/ en sí (tomo
I de las OC.GS, p. 1245). Se trata no de /la vida de la conciencia de
NicoMagik, PatriciaPsicóloga, RobertoPadre, etc., etc./ sino de la vida
de la conciencia qua conciencia universal. *Conciencia Trascendental* es
aquello que es común a todo los individuos racionales, etc. Por eso
coincide con una *Lógica Trascendental*. El punto es si hacer está
afirmación supone substancializar tal lógica trascendental en una
objetividad (el famoso "sujeto trascendental"), pero en fin, me estoy
yendo mucho de mambo. Volvamos al Husserl ético.

Para Husserl, dice Heidegger, "lo categorial nos es dado". Lo
revolucionario del método fenomenológico, dice Heidegger, es haber hecho
tanto hincapie en este punto. Hay lo mismo que una *intuición sensible*,
una *intuición categorial*. Y dicha intuición categorial sirve lo mismo
para los juicios de existencia, como predicativos, como de identidad,
como valorativos, como afectivos, etc., etc («/lo categorial, de la
misma manera que lo sensible, nos es dado (gegeben)/»). En efecto, las
categorias nos son dadas, los valores nos son dados, y en una actitud
correcta, esto implica la posibilidad de fijar objetivamente el
resultado de las operaciones intuitivas de la conciencia. De esta forma
se superan todos los escepticismos-relativismos: no solo el
lógico-gnoseológico.

Por lo mismo dice el Introductor, la fenomenología sirve para
fundamentar propuestas éticas como las de Jürgen Habermas y Ernesto
Tugendhat, mostrando que los valores surgen de sentimientos (si bien de
/sentimientos éticos/, no de cualquier tipo de estado afectivo). El
fundamento, en el sentido ontológico-formal de los valores, reside para
ellos en sentimientos propios del Mundo de la Vida (esta gente no habría
realizado, todavía, la "/inversión spinozista/" con la cual todavía no
sabemos si nos comprometemos, pero al menos pudimos contemplar como una
posibilidad para la fenomenología o, lo que es decir lo mismo, la verdad
de El Mundo). El punto igual, dice el comentador, es que /Esto nos lleva
a afirmar que ciertamente la ética trata de sentimientos morales, así no
se exprese en última instancia en meros sentimientos sino en juicios/
(cf. Hua XXVIII, 390-391).

Allí se tematiza ya el asunto de la moral en relación con el sujeto de
la acción y se rompe en cierta forma con una analogía rigurosa del
análisis intencional de la ética con el de la lógica:

#+BEGIN_QUOTE
  «[...] nada se exige a priori objetivamente de un sujeto, que fuera
  inalcanzable para él. Lo que alguien no puede, tampoco debe hacerlo.
  La intención que tiene el predicado de deber tiene predicación más
  rica que el de conveniencia. Y ahora vemos, pues, que ya con esta
  ampliación la subjetividad juega un papel, que no tiene ninguna
  analogía en el campo del juicio y de la verdad » (Hua XXVIII, 149).
#+END_QUOTE

** I RENOVACIÓN. EL PROBLEMA Y EL MÉTODO (M)
   :PROPERTIES:
   :CUSTOM_ID: i-renovación.-el-problema-y-el-método-m
   :END:

Husserl comienza con el diagnóstico pesimista de una fue en la cultura,
perdida, una fe que "Si antes de la guerra ya se tambaleaba, hoy se ha
derrumbado por completo. Tal es el hecho ante el que, como hombres
libres, nos encontramos. Él debe determinar nuestra praxis" (1). Husserl
afirma la voluntad libre como una suerte de primer principio no
justificado, punto de partida a aceptarse: intervenimos activa y
libremente en el mundo, lo hagamos bien o mal, queramos o no. Sin
embargo, parecería que esa libertad no está guiada racionalmente y he
ahí el problema. Contra los partidarios de la /Realpolitik/ que niegan
la libertad como ilusión, Husserl viene a afirmar la necesidad de guiar
racionalmente la voluntad humana libre.

Retomando el espíritu de aquel Platón que veía su Atenas tambalear
frente a la amenaza sofista, Husserl ve su época acechada por el
pesimismo escéptico y "la desvergüenza de la sofística política que tan
fatalmente domina nuestro tiempo, y que se vale del discurso de la ética
social sólo [4] como disfraz de los fines egoístas de un nacionalismo
totalmente pervertido [...]". Esto es posible sólo gracias a que se
fundamenta, por así decir, en problemas conceptuales, en "horizontes de
oscuridad". Por eso el remedio para el problema es la *ciencia
estricta*, que, aclarando dichos problemas, logre fundamentar el actuar
ético y responsable.

Las ciencias naturales y exactas han logrado, si bien a cierto coste, la
rigurosidad deseada que ha permitido la racionalidad práctica en la
esfera técnico-natural. Falta por completo, empero, la ciencia rigurosa
"del hombre y la colectividad humana" que fundamenten la acción social y
la técnica política racional. Falta, entonces, la ciencia que acometa la
/idea de hombre/ en su par individuo-comunidad, ciencia apriori que haga
con el hombre lo que la matemática hizo en relación con la naturaleza.
Existen ciencias empíricas relativas al humano, pero son meramente
empíricas. Carecen de la fundamentación en "la /mathesis del espíritu y
de la condición humana/" (5)

Pero respecto de las ciencias del espíritu no basta con la 'explicación
racional', como ocurre en el caso de las ciencias naturales, sino que se
hace necesaria otra forma de racionalización de lo empírico: la
normatividad.

Respecto de esta ciencia del espíritu señala Husserl tres
características fundamentales, que la distinguen de la ciencia de la
naturaleza:

1. Cada realidad espiritual individual posee una /vida de conciencia/
   cerrada sobre sí y referida a un polo /yo/ que centra todos los actos
   en /conexiones de *motivación*/
2. Estas realidades individuales entran en relaciones entre sí, de
   comprensión mediante la /empatía/, que da lugar /actos sociales/ que
   dan lugar, a su vez, a nuevas realidades: las *colectividades*.
3. A los actos y sus motivaciones pertenecen diferencias relativas a la
   /razón/, que dan lugar a la diferencia entre pensar y valorar
   *correctos e incorrectos*.

La esencia peculiar de lo espiritual que se manifiesta en la vida de la
conciencia no puede ser racionalmente explicada por vía
causal-inductiva, empíricamente, sino que debe efectuarse un retroceso a
las leyes esenciales a las que peretence la figura normativa de la
/razón/: lógica, estimativa y práctica. A esta razón puede seguirle el
sujeto que libremente actúa siguiendo la norma en la práctica. Por lo
tanto, pertence a la ciencia apriórica el dominio de la práxis normativa
que guía la vida libre del sujeto.

Así, del hecho de que formulemos juicios reprobatorios sobre le estado
de nuestra cultura, se sigue que creemos en una 'buena humanidad' como
posibilidad ideal. En el juicio mismo, entonces, está ya implícita la
creencia en la verdadera y auténtica humanidad como idea objetivamente
válida, según la cual hay que guiar la tarea de la renovación. Así, es
la idea de una /humanitas/ auténtica la que debe determinar las figuras
tanto individuales como colectivas de la praxis racional que bsuca la
renovación.

** II EL MÉTODO DE LA INVESTIGACIÓN DE ESENCIA (Emiliano)
   :PROPERTIES:
   :CUSTOM_ID: ii-el-método-de-la-investigación-de-esencia-emiliano
   :END:

El método de investigación de esencias es el método de *intuición de
ideas* Y de *conocimiento predicativo de ideas*, es un método /a priori/
cuyo /a priori/ es el mismo que el de las matemáticas puras, al que no
tocan las interpretaciones empiristas o metafísicas del mismo. Mutatis
mutandis, Husserl pretende lo mismo para la filosofía. Lo mismo que hace
la matemática respecto a las objetividades que les son propias, puede
hacerse respecto a cualquier correlato de vivencia o a cualquier
realidad de la que tenemos experiencia. Lo mismo que el matemático se
abstiene de pronunciarse acerca de la /realidad objetiva/ de sus
objetos, lo mismo hace el fenomenólogo. En este sentido, para su
proceder formal, puede empezar tanto por objetos reales como
imaginarios: puede variar libremente lo mismo un cuadrado dibujado que
un cuadrado imaginado, para llegar, así, a la esencia "cuadrado". Su
tema no es la naturaleza real, sino una naturaleza posible en general.
La libertad de la matemática, lo mismo que la de la fenomenología, es la
libertad de la fantasía pura y del pensar puro en la fantasía. La
sujeción a leyes de la variabilidad es lo que se ha de encontrar, y en
ello consiste la esencia de lo tematizado vía la fantasía libre.

La variabilidad de la representación fantaseante se acepta en tanto que
algo se mantenga *idéntico*. Es esa identidad el tema último del
matemático o del fenomenólogo. Se acepta la variabilidad mientras se
mantenga idéntica la misma realidad (por eso no se ocupa de lo real,
sino de los *posibles idealiter*). Así, progresando a través de la
fantasía llegamos al terrotorio propios de las esencias o de las ideas
puras o esencias y las leyes de esencia. Bajamos desde allí a los
teoremas mediatos, demostrados mediante deducción, etc, etc.

#+BEGIN_QUOTE
  Los conceptos fundamentales que el matemático engendra originariamente
  en intuición general son generalidades puras, intuidas directamente
  sobre las individualidades fantaseadas; sobre la base de la libre
  variación de estas individualidades, las generalidades se destacan
  como el sentido general idéntico que las atraviesa y que en ellas se
  individualiza (la methexis platónica en su intuición originaria).
#+END_QUOTE

Así por ejemplo, la posibilidad pura de un único cuerpo físico, que una
fantasía clara y congruente nos pone ante los ojos, depara a la vez
---por libre variación del cuerpo físico, y en la conciencia de que esta
variación es susceptible de prosecución ad libitum--- la conciencia
originaria de una infinitud abierta de posibles cuerpos físicos. Ante la
mirada abarcadora que sobrevuela la infinitud abierta de variantes, lo
idéntico que se mantiene fijo en la variación se alza con evidencia como
identidad que atraviesa las variantes, como la esencia general común a
ellas, como su idea. O lo que es lo mismo, resulta su «concepto puro»
común, visto intuitivamente: el concepto de un cuerpo físico en general,
que está referido a esta infinitud de posibilidades ideales singulares
como a su «extensión ». Con conceptos obtenidos originariamente de este
modo opera la matemática; ella engendra las leyes de esencia inmediatas
---los llamados axiomas--- que corresponden a tales conceptos como
verdades «necesarias y generales en sentido estricto», «que no admiten
la posibilidad de excepción ninguna en absoluto» (Kant). La matemática
intuye, desde luego, estas verdades como situaciones generales de
esencia, que en absoluta identidad se dejan producir para todas las
individuaciones pensables de sus conceptos puros ---para esas
infinitudes de variación fijamente cerradas o «extensiones »
aprióricas---, y que con evidencia se dejan reconocer como tales
situaciones generales. A partir de ellas engendra luego en intuición
deductiva («evidencia» apriórica de la consecuencia necesaria) sus
teorías y «teore-[16]-mas» derivados, de nuevo como identidades ideales
captables con evidencia intelectual en toda repetición que las produzca.
Cualquier posición judicativa concomitante de realidades de la
experiencia, como las que comportan todos los conceptos empíricos (por
ejemplo, los conceptos de historia natural: león, lagarto, violeta,
etc.) y, por su medio, todas las proposiciones empíricas generales, se
mantiene rigurosamente inhibida. En este sentido, lo que el pensar
matemático establece es completamente a priori frente a toda empiria. En
cambio, todo lo que es pensable como individuo de conceptos «puros», y
supuesto que tenga que poder mantenerse la identidad de su ser posible,
cae bajo las leyes «de esencia» o leyes «puramente conceptuales» del
caso.

** III RENOVACIÓN COMO PROBLEMA ÉTICO INDIVIDUAL (M)
   :PROPERTIES:
   :CUSTOM_ID: iii-renovación-como-problema-ético-individual-m
   :END:

*** 1. Formas de vida autorreguladas como formas previas de vida ética.
Introducción al tema
    :PROPERTIES:
    :CUSTOM_ID: formas-de-vida-autorreguladas-como-formas-previas-de-vida-ética.-introducción-al-tema
    :END:

#+BEGIN_QUOTE
  "La /ética pura/ es la ciencia de la esencia y formas posibles de una
  vida en renovación tomada en generalidad pura (apriórica). La ética
  /empírica-humana/ se propone luego adecuar las normas de la ética pura
  a lo empírico; aspira a convertirse en la guía del hombre en la Tierra
  en las condiciones que le están dadas (individuales, históricas,
  nacionales, etc.)" (21)
#+END_QUOTE

Además de la ética individual existe la /ética social/, esto es una
ética de las colectividades en cuanto tales. Una colectividad universal
es una humanidad y la unidad de ésta está determinada por la /cultura/,
cuya definición reza:

#+BEGIN_QUOTE
  "Por cultura no entendemos otra cosa, en efecto, que el conjunto total
  de logros que vienen a la realidad merced a las actividades incesantes
  de los hombres en sociedad y que tienen una existencia espiritual
  duradera en la unidad de la conciencia colectiva y de la tradición que
  la conserva y prolonga" (22)
#+END_QUOTE

La colectividad puede adoptar por sí esta forma superior de vida y
devenir una /personalidad de orden superior/, esto es: la colectividad
puede llevar a cabo sus propios logros entendidos no como la suma de
individuos que pertencen a una misma colectividad, sino como el
esfuerzo, voluntad y logros propios de una colectividad en tanto tal.
Así, "La vida activa de una colectividad, de toda una humanidad, puede
también, en consecuencia, adoptar la figura unitaria de la razón
práctica, la figura de una vida «ética» ---por más que en ninguna
realidad histórica anterior haya ocurrido así" (23). La vida de la
colectividad/humanidad se concibe en analogía con la del individuo: se
trata igualmente de un proceso de renovación que nace de la voluntad
expresa de configurarse a sí misma como humanidad auténica según la
razón práctica.

**** A. El hombre como ser personal y libre
     :PROPERTIES:
     :CUSTOM_ID: a.-el-hombre-como-ser-personal-y-libre
     :END:

Rasgos de esencia del ser humano en general:

1. *Capacidad de autoconciencia* entendida en el sentido del autoexamen
   personal (el conócete a ti mismo socrático), capacidad de tomar
   postura reflexiva respecto de sí mismo y la propia vida. Actos
   personales de autoconocimiento, autovaloración y autodeterminación
   práctica.
2. *Actuar libre y activamente desde sí mismo* en lugar de ser movido
   pasivamente por impulsos.
3. *Sopesamiento crítico de los actos libres de orden singular o
   general*.
4. *Discurrir en la forma del empeño, afán*. Este suele ser un empeño
   /positivo/ que se encamina a la consecución de /valores positivos/.
5. *Vivir en lucha por una vida plena de valor*
6. *Empeño de la razón*: "es un empeño por dar a la vida personal, a sus
   tomas de postura judicativas, valorativas y prácticas, la forma de la
   evidencia, de la clarividencia, o bien, por adecuación a ésta, la
   forma de la legitimidad, de la racionalidad" (27).

**** B. Formas de vida específicamente humanas y formas preéticas de
autorregulación
     :PROPERTIES:
     :CUSTOM_ID: b.-formas-de-vida-específicamente-humanas-y-formas-preéticas-de-autorregulación
     :END:

En la posibilidad de autoconfiguración libre del ser humano se fundan
las formas de vida específicamente humanas, que H. llama "/tipos de
personalidades humanas/" [2], distintas entre sí a priori y que
ascienden hasta la forma suprema de valor del /hombre ético/. El hombre
puede reflexionar sobre su propia vida y puede tamibén proponerse una
/meta general de vida/ a la que somete su vida entera. Un rasgo genérico
es la entrega /incondicional/ a estas metas, incluso cuando éstas son
irracionales y no producto de la reflexión crítica fundada en la ética.

"Un caso especial de preferencia incondicional es el de la decisión por
una /vocación de vida en un sentido genuino y superior al de la
profesión/" (29). Esta se define por el amor y la entrega a estos
valores, que admite la comprensión de la heterogeneidad de los valores,
pero no ama ni se entrega a los diferentes. Es una forma preética en
tanto reconoce una meta y actúa en pos de ella, pero no aún la meta más
alta de ser un hombre ético:

#+BEGIN_QUOTE
  "En ello sí se anuncia una diferencia esencial respecto de lo
  anterior, por cuanto yo puedo respetar por entero y apreciar valores
  heterogéneos, pero lo que no puedo es amarlos desde el centro más
  íntimo de mi persona ---«con toda mi alma»---: amarlos como los míos,
  como aquellos a los que yo mismo, tal como soy, pertenezco
  inseparablemente. Mas así es el arte «vocación» del auténtico artista,
  y la ciencia «vocación» del auténtico científico (del «filósofo»):
  dominio de actividades y logros espirituales al que alguien se sabe
  «llamado», y de manera tal que sólo la creación de los bienes
  correspondientes le reporte la «más íntima» y «pura» satisfacción, le
  traiga con cada nuevo éxito la conciencia de «ser dichoso»." (30)
#+END_QUOTE

*** 2. La forma individual de vida de auténtica humanidad
    :PROPERTIES:
    :CUSTOM_ID: la-forma-individual-de-vida-de-auténtica-humanidad
    :END:

La forma de vida del hombre ético es la única /absolutamente valiosa/.
Toda forma de vida se ordena en pos de la vida ética. El hombre
auténtico es lo que es (auténtico filósofo, por ejemplo), sólo en tanto
la vida ética lo exige de él.

**** A. Génesis de la renovación como autorregulación absoluta y
universal. Razón, felicidad, satisfacción, conciencia moral
     :PROPERTIES:
     :CUSTOM_ID: a.-génesis-de-la-renovación-como-autorregulación-absoluta-y-universal.-razón-felicidad-satisfacción-conciencia-moral
     :END:

La diferenica entre el hombre auténtico ético y el (mero) profesional
auténtico recae en que el primero autoregula éticamente /todas/ sus
acciones y no solamente aquellas relativas a lo profesional.

Es específico del hombre el poder contemplar su vida /entera/ como
"unidad /objetivamente/ constituida ante él". Quien hace esto teniendo
ya una meta de llevar una vida ética auténtica se encuentra con la
multiplicidad e intrincación de sus proyectos prácticos y planes y crece
así su inseguridad e inquietud por dar con los bienes auténticos y
duraderos. Dada esta "interdepencencia funcional de los valores
prácticos", se siguen ciertas leyes éticas esenciales:

1. *Ley de absorción*: "Donde múltiples valores pueden ser realizados
   por un mismo individuo en un mismo instante de tiempo, siendo, en
   cambio, imposible su realización colectiva (por pares o en conjunto),
   la bondad del más alto de estos valores absorbe la bondad de todos
   los valores inferiores». Quiere esto decir que la elección de
   cualquiera de esos valores «absorbidos» es errónea; dondequiera que
   un bien práctico superior entra en competencia con ellos, dejan ellos
   de ser bienes prácticos y son males"
2. *Ley de sumación*: "la realización colectiva de bienes prácticos que
   no sufren con ello merma en su valor, depara «un bien sumativo» de
   mayor valor que el de cada una de las sumas parciales o miembros
   individuales"

La /conciencia de la responsabilidad de la razón/ o conciencia moral
surge en determinadas situaciones en las que el hombre cobra
conocimiento de que es posible una justificaicón evidente para su actuar
y especialmente cuando cobra conciencia de que esta justificación debe
preceder y guiar la acción y no aparecer /a posteriori/.

**** B. La forma de vida de auténtica humanidad
     :PROPERTIES:
     :CUSTOM_ID: b.-la-forma-de-vida-de-auténtica-humanidad
     :END:

#+BEGIN_QUOTE
  "Si avanzamos aquí hasta el límite ideal, hasta el limes en términos
  matemáticos, se destaca por sobre el ideal relativo de perfección un
  ideal absoluto. No es otro que el ideal de la perfección personal
  absoluta: absoluta perfección teórica, axiótica y en todos los
  sentidos de la razón práctica. Se trata, pues, del ideal de persona
  como sujeto de todas las facultades personales que se dejan potenciar
  en el sentido de la razón absoluta; ideal de una persona que, de
  pensarse simultáneamente como omnipotente o «todopoderosa», poseería
  todos los atributos divinos. En todo caso, y excepción hecha de esta
  diferencia suprarracional, podemos decir: el limes absoluto, el polo
  que trasciende toda finitud, al que todas las aspiraciones
  auténticamente humanas se dirigen, es la idea de Dios. La idea misma
  de Dios es el «yo auténtico y verdadero», que ---como habrá que
  mostrar--- todo hombre ético lleva en sí mismo, que anhela
  infinitamente y ama infinitamente y de la que se sabe siempre
  infinitamente lejos. Frente a este ideal absoluto de perfección, se
  encuentra el ideal relativo, ideal del ser humano perfectamente
  humano, que hace «lo mejor» que está en su mano, que vive según la
  «mejor» conciencia moral que le es dada ---un ideal éste que lleva ya
  impreso el sello de la infinitud" (35)
#+END_QUOTE

**** C. Aclaraciones y complementos
     :PROPERTIES:
     :CUSTOM_ID: c.-aclaraciones-y-complementos
     :END:

El errar es tanto una posibiliadad esencial abierta como una posibilidad
fáctica inevitable [3], que se sigue de la sola relación entre le hombre
y su entorno. El hombre en el edén, dice Husserl, sería infalibe, pero
no como la infalibilidad de la perfección divina, sino sólo en tanto que
no habría errores para cometer.

El hombre verdadero es el que se somete al /imperativo absoluto/ que no
dice más que:

#+BEGIN_QUOTE
  "Sé hombre verdadero. Conduce tu vida de modo que siempre puedas
  justificarla en la evidencia. Vive en la razón práctica".
#+END_QUOTE

Esto tiene el carácter de un ideal regulativo, por lo tanto, ser hombre
verdadero, ser /auténticamente humano/, es más bien vivir siempre
*intentando* ser hombre verdadero, hacer siempre lo mejor posible.

El comienzo del autodesarrollo es la imperfección que toma como meta la
perfección. Esto, sin embargo, no basta. Siempre cabe la posiblidad de
caer en una vida /pecaminosa/, que no es retorno a la ingenuidad, sino
transgresión de la norma. La desatención a las normas y la falta de
reflexión sobre la propia vida pueden llevar a una /pecaminosidad
endurecida/, una vida caracterizada por la falta de conciencia moral,
producto de las decisiones libres del sujeto.

#+BEGIN_QUOTE
  "Llamamos en general y en el sentido más amplio «vida ética» a toda
  vida que se gobierna a sí misma conforme a la exigencia categórica de
  la idea-meta de naturaleza ética (también, pues, a la que no es
  enteramente coherente). Y llamamos al sujeto de esta vida, como sujeto
  que se determina a sí mismo a una autodisciplina ética, personalidad
  ética ---también en el sentido más amplio"
#+END_QUOTE

El carácter esencial de lo ético consiste en guiar /toda/ la vida según
el imperativo categórico de la razón. Así, el quehacer del científico
(del profesional) es una conducta ética. Husserl se pregunta si la forma
de vida vocacional-profesional puede justificarse en el marco de la vida
regida por el imperativo. El imperativo categórico es una forma vacía de
contenido que debe ser dotado de contenido por una ética desarrollada en
referencia al individuo:

#+BEGIN_QUOTE
  "Cada hombre tiene, pues, además de su individualidad, su idea ética
  individual y su método ético individual, su imperativo categórico
  individual determinado en concreto para su caso. Sólo la forma general
  de esencia del hombre ético y de una vida bajo el imperativo
  categórico formalmente idéntico, es común a todos los hombres en
  cuanto tales; y comunes son también, naturalmente, todas las normas
  aprióricas que una ética científica y fundamental (formal, por tanto)
  sea capaz de deducir de la «esencia» del ser humano"
#+END_QUOTE

*Reino de la cultura del individuo*: la totalidad de los bienes
subjetivos (especialmente auténticos) producto de las actividades
personales (especiametne de las racionales)

** IV RENOVACIÓN Y CIENCIA (Emiliano)
   :PROPERTIES:
   :CUSTOM_ID: iv-renovación-y-ciencia-emiliano
   :END:

(!): Por momentos Husserl llama a la "humanidad auténtica" con el
término técnico /humanitas/.

Husserl parte de esta pregunta: ¿Cómo es posible la renovación de una
cultura? Para responderla, se propone resolver como primera cuestión el
problema de la meta de la renovación, esto es, constituir una *cultura
verdadera*, una *vida colectiva verdadera*. Una vez resuelto este
problema, haría falta acometer el problema de la *transición* desde una
cultura inauténtica a una vida colectiva verdadera. Hay que notar, acá,
que Husserl distingue en dos cuestiones lo que uno tiende a ver como una
sola:

1. La Revolución como la transición del Estado Actual a un Nuevo Estado
   Utópico.
2. La Revolución como el nombre del nuevo estado utópico. [%*A esto nos
   referimos normalmente como la 'sociedad post-revolucionaria', al
   menos yo...*]

Cada una de esas preguntas (1. y 2.) tiene sus propias respuesta.
Fantaseosas, como las de la Revolución Cyberpunk, o whatever. Pero eso
es 1. El problema es pensar que cualquiera de los dos es independiente.
Es decir: creer que al asegurar la objetividad de los valores de la
cultura verdadera, la "forma" de alcanzar tal estado va a estar dada por
añadidura, o lo contrario, pensar que siendo capaces de captar la forma
de la transición, la meta luego se realizara por añadidura, por mera
oposición a lo anterior.

Husserl encuentra una pregunta que de alguna manera engloba ambas
problemáticas:

#+BEGIN_QUOTE
  α) Cuestión de si pertenece a la esencia de la colectividad y de la
  vida colectiva el que sólo puedan tomar la forma de colectividad
  «auténticamente humana» a partir de una forma inferior desde la que se
  eleven al estadio «auténticamente humano » ---forma inferior: vida que
  no es verdaderamente humana, que está acaso en el nivel de una
  comunidad «animal» o de comunidad humana en un estadio falto de valor.
  La cuestión, pues, de que no puede haber desde un principio una
  colectividad propiamente «humana», sino que sólo puede haberla por
  medio de un desarrollo, por medio de un proceso de devenir, continuo o
  discreto, pasivo, activo o comoquiera que sea, pero que lleve a
  término una completa transvaloración, una trasmutación o inversión de
  los valores.
#+END_QUOTE

¿Podría un conjunto de hombres, por mera reflexión
eidético-fenomenológica, crear una sociedad auténticamente humana?
¿Puede llegarse a la comprehensión de lo /verdaderamente humano/ desde
el vacio, y a partir de esa comprehensión, fundar verdaderamente una
comunidad capaz de realizar lo verdaderamente humano? Este es el
problema que lo preocupa acá. Las alternativas parecieran dos. 1) que sí
se puede, 2) que no se pueda, que sea necesario progresar desde una
forma inferior de vida, a una forma superior (en un esquema tipicamente
hegeliano, aunque todavía no se encuentra el momento de negación).
Husserl parece decantarse por 2. El surgimiento de una comunidad
verdaderamente humana es un proceso necesariamente histórico, de
ampliación de los valores, progresivo, etc., etc. Es por ello que "la
revolución" tiene sentido. Si no, no haría falta ninguna "revolución" en
el sentido literal de esta palabra, sino una mera "fundación" de una
comunidad nueva (cfr. los proyectos de la comunidad patagónica de Mati,
con la revolución Cyberpunk, etc., etc.).

Ahora bien, supongamos que nos decidimos por 2. En principio parece
fácil: ya vivimos en una cultura, la cultura es inauténtica, se trata de
llevarla entonces a la autenticidad. Habría que ver cuáles son los
medios para lograr tal transición y cuál es la meta de la misma. Pero
Husserl se pregunta, precavido, respecto a si esto es realmente una
posibilidad esencial:

#+BEGIN_QUOTE
  α') Cuestión de en qué medida la reconstrucción de una cultura
  inauténtica en una auténtica puede ser un fin práctico sujeto a la
  voluntad, y a una voluntad que tenga carácter de voluntad colectiva,
  de suerte que sólo pueda existir una colectividad propiamente humana
  si ella deliberadamente se ha resuelto a sí misma a la humanitas. α“)
  Cuestión de los caminos que sirven a este propósito.
#+END_QUOTE

En definitiva, Husserl comienza su apartado IV RENOVACIÓN Y CIENCIA,
preguntándose por las condiciones de posibilidad de una revolución. No
es marxista, obvio, él no ve -como ve Marx- que una *renovación
espiritual* tenga que fundamentarse, necesariamente, en una *revolución
material* (de las condiciones mismas del trabajo, etc). Y sin embargo,
la pregunta por la RENOVACIÓN de la cultura es exactamente la misma que
la pregunta por la REVOLUCIÓN de la sociedad.

Para responder a estos interrogantes, Husserl parte de una reflexión
respecto de la meta. Pero la meta de la sociedad y las metas de los
individuos al interior de tal sociedad son dos caras de la misma moneda.
Para Husserl, entonces, vivir en una comunidad implica vivir bajo un
determinado "imperativo ético". No se puede vivir de cualquier modo,
siempre hay valores, metas, propósitos hacia los cuales apuntamos.
Heidegger dirá luego: siempre nos "temporizamos". Pero acá Husserl va
todavía más lejos: no nos temporizamos solo en función de metas
prácticas o deseos contingentes, sino en función de un cierto
"Espíritu", de una cierta "Ley" para decirlo Hegeliana/Lacanianamente.
De hecho tenemos la posibilidad de no vivir de esa manera, pero
entonces:

#+BEGIN_QUOTE
  Es más, el ir viviendo ingenuamente irreflexivo lleva al pecado. El
  hombre carga como hombre con el pecado original que pertenece a la
  forma de esencia del hombre.
#+END_QUOTE

La autenticidad implica hacernos cargo de nuestros proyectos y de
nuestras metas *reflexivamente*. Saber quiénes somos, qué queremos y
mantenernos /atados/, fieles a tales propósitos. Incluso cuando tales
metas sean incorrectas bajo la perspectiva de "la verdad" (de la
reflexión fenomenológica en que se nos dan /las cosas mismas/). Hay una
invariante formal anterior a la especificación del contenido material:
ser fieles a las metas que decidimos como las correctas. Osea, evitar la
/irracionalidad/, ser coherentes, evitar la /akrasia/ es el primer
momento, ineludible, de la moralidad. En otras palabras: no actuar mal a
sabiendas. No ser Medea. Etc. La teoría ética socrática, que decía que
ningún hombre actua mal a sabiendas es inexacta. Sócrates mismo ve que
hay hombres que actuan mal no a sabiendas, pero sí por causa de una
actitud irreflexiva. "Educar a la humanidad" para que no se comporte de
manera irreflexiva, sería el paso uno para la renovación ética de la
humanidad. Una cultura auténtica, sería aquella en que todos los hombres
se comprometen a evitar la akrasia en un sentido radical: a evitar la
akrasia mediante la reflexión respecto a los fines prácticos y a los
medios de alcanzarlos, para la propia vida. Un nuevo /pacto social/ nos
comprometería, entonces, con una suerte de auto-examinación constante
(casi católica, de confesionario; pero también psicoanalítica, de
consultorio) con nuestras propias inclinaciones vitales.

#+BEGIN_QUOTE
  Como hombre, él es sujeto de la autorreflexión, y sujeto de la toma de
  postura valorativa y práctica en relación consigo mismo; sujeto, pues,
  de «conciencia moral» que, como tal está bajo una norma absoluta de
  valor: debe en cada caso decidir su conducta práctica según su mejor
  ciencia y conciencia; no debe dejarse llevar pasivamente por la
  inclinación, sino libremente querer el bien y libremente decidirse por
  el bien, por lo que cognoscitivamente reconoce ---aunque quizá en el
  error--- como el bien. Sólo así puede ser «hombre bueno».
#+END_QUOTE

En efecto, el primer momento de la moralidad es puramente formal: actuar
reflexivamente, no dejarnos llevar por nuestras inclinaciones
momentaneas.

#+BEGIN_QUOTE
  En definitiva, puede reconocer que se halla bajo el imperativo
  categórico de adoptar tal opción de vida y que sólo se hace bueno si
  hace suyo el imperativo en su voluntad.
#+END_QUOTE

Pero, ¿quién puede hacer eso hoy en día? Ciertamente, yo no puedo. Quizá
el problema es que para adoptar tremendo compromiso, uno debe poder
haber visto la meta con la cual comprometerse previamente. Y no tenemos
eso. Tenemos, cuando mucho, a veces "la sensación" de que algo está mal.
Pero sin saber lo que es bueno, ¿cómo poder saber lo que es malo? ¿Cómo
comprometernos a evitar la akrasia entonces? Ese es quizá el tema
contemporáneo más relevante. Husserl debe haberlo visto, pero no se lo
plantea de esa forma: no es posible, diría, resolver tal cuestión en el
vacío. La única forma de darle una solución es encontrar los valorse
objetivos que nos puedan volver los mejores hombres posibles. Pero,
hegeliana-kantianamente, entiende que hay un momento meramente formal
que también ha de describirse, aún cuando el mismo no sea propiamente
hablando "anterior" [%2 *Sería anterior lógicamente, aunque no
temporalmente, ¿no?*] a la captación de alguna meta material.

Lo siguiente es fundamental y lo cito en extenso entonces:

#+BEGIN_QUOTE
  Pero con ello este hombre no es ya, sin embargo, el mejor hombre
  posible en absoluto. Más bien vive ahora en una lucha diaria, y no
  deja de tomar nuevas decisiones y se siente responsable de ellas. Las
  pasiones pasan por encima de su buena voluntad, y se ve movido a
  meditar acerca de cómo asegurarse frente a ellas ---acerca de cómo
  debilitar la fuerza que tienen sobre él, o de cómo fortalecer su
  propia fuerza frente a ellas. Ocurre también que equivoque gravemente
  el juicio acerca de las circunstancias relevantes, que yerre en los
  medios y elija lo lesivo en lugar de lo útil, o el valor menos noble
  en lugar del de mayor nobleza. O que enjuicie erróneamente a otros
  seres humanos, y sin que le mueva ningún motivo egoísta, aun viviendo
  en el amor sincero hacia los hombres, les haga injusticia, y al
  herirlos se hiera también a sí mismo. Experiencias de este tipo le
  enseñan que es imperfecto, que ha de aprender a guardarse del error, a
  reflexionar sobre su capacidad cognoscitiva, etc. Junto a la
  responsabilidad por cada decisión individual, contrae una preocupación
  responsable por la preparación de las capacidades y fuerzas que de
  manera general pueden asegurarle mejores posibilidades de decisión
  individual en determinadas clases de situaciones. Y el hombre no vive
  en solitario, con lo que también aquí cuenta la influencia de la
  observación de los otros, lo que se aprende de su lucha diaria, la
  preocupación por contar con modelos nobles, etc.
#+END_QUOTE

Lo propio de la actitud ética no es no cagarla nunca, sino ser capaz de
reconocer el error. Por lo mismo Jehova no exige una voluntad
completamente firme a lo largo del tiempo . . . sino el arrepentimiento
cuando corresponde. El hecho mismo de que tengamos deseos contingentes
implica que no podemos vivir en una actitud espiritual universal,
trascendente, infinita constantemente. Pero sí podemos remitirnos a ella
cuando hace falta, para actuar conforme a una norma infinita y no
mantenernos en el error. No se trata de no errar nunca, sino de no
mantenernos en el error.

Pero además de esto, dice Husserl, el hombre vive siempre en una
comunidad humana, lo que vuelve más relevantes las demandas éticas
propias de su estar-en-el-mundo. La conducta ética no tendrá que ver tan
solo con los fines que se proponga para su vida finita (finita en el
tiempo) sino con aquello que dé o deje de dar, con aquello que pueda
regalar u otorgar a la comunidad como un todo, y a los individuos
concretos con los que me cruce en mi vida-cotidiana, como parte de mi
Umwelt o las esferas sociales por las que circule. Por eso en mi
relación con Debora siempre me ponia tan ansioso que fuera manifiesto,
de alguna manera, el "bien" que le hacía. Por eso cada vez que
terminamos una reunión con Mati le pregunto: ¿avanzamos algo? Pero
habría que preguntarse qué significa acá que la /ansiedad/ sea en parte
el motor afectivo de esa actitud. Pero no, la /ansiedad/ aparece siempre
/a posteriori/, como duda respecto al logro de la meta que me propuse
previamente. Y en definitiva, todo discurso ético tiene que enfrentarse,
tarde o temprano, a la problemática concreta de los resultados de
nuestras acciones. En cierto sentido, una ética formal no se preocupa
por los resultados. Eso es Kant. Kant, en cierto sentido, es formal y
material, dado que hay metas concretas a las que se accede mediante el
imperativo categórico. Pero los resultados a los que nos lleva el actuar
respecto a las metas materiales no tienen, para él, mayor consecuencia.
Y sin embargo, la /ansiedad/ esta que estoy mentando vuelve a aparecer
en posteriores actuaciones. No se puede evitar considerar la manera en
que los resultados de nuestras acciones generan un horizonte de
protensiones-ética, por así decirlo, que nos determinan en nuevas
circunstancias prácticas.

Se trata ante todo de tener una /voluntad buena/, una /voluntad recta/.
Dicha voluntad traería, para Husserl, bienes verdaderos, auténticos. El
problema es que el enlace entre la voluntad buena y los bienes
auténticos no es tan inmediato como considera Husserl. Probablemente
todo resultado está mediado por el horizonte ideológico, por el
entramado ideológico-social de la comunidad a la que pertenecemos. Podes
tener una voluntad recta, y no ocasionar ningún bien auténtico en el
otro, porque el otro "no sabe" actuar frente a una voluntad recta. A
Jesús lo crucifican, etc., etc. Claro, tuvo discípulos. Pero, ¿y sino
los hubiera tenido? ¿Cuál es el sentido último de la vida de Jesus en un
mundo-paralelo, posible, sin discípulos? O pensemos en un
"revolucionario". Pero falla en su realizar-la-revolución. ¿No debe, la
/voluntad recta/, realizar un cálculo racional de los resultados de sus
acciones para poder considerarse tal? Sin una consideración de la
/transición/ de la voluntad buena, de la voluntad recta a los resultados
concretos, a los bienes auténticos pero partículares de sus acciones,
pareciera que algo falla. Y Husserl posta que no lo ve, lo mismo que
Kant no lo vio. Por otro lado, hay una tensión horrible en esta
problemática. Tampoco sería justo juzgar a la buena voluntad, a la
voluntad-recta, por los resultados ominosos de sus acciones. Si el Mundo
(si el horizonte histórico-partícular de un Lebenswelt histórico-social
determinado) se le resiste, ¿ha de ponerse del lado de la voluntad
auténticamente-recta algo de la responsabilidad por el fracaso de a su
accionar? Este es el problema, cuya solución es ciertamente "espinoza".

La primera consideración, como siempre, es considerar al otro como un
fin en sí mismo, como un "bien-en-sí-mismo" y no como un medio-para,
como un bien útil, que me permitira realizar tales o cuales metas
concretas, prácticas, que me impuse para mi vida. Si trato al otro como
"el novio que quiero tener", porque quiero estar de novio, porque quiero
eso para mi vida práctica, por ejemplo, el otro deja de ser un bien
inmediato y se transforma en un bien-utilitario, en un medio para un
fin, con lo que rompo completamente la posibilidad de un relacionarme
ético con el otro. "/En el trato social, este individuo advierte, que el
otro, en la medida en que es bueno, tiene un valor también para él, y no
un mero valor de utilidad sino un valor en sí./" Aquello que desee, debo
desearlo como un fin en sí mismo. Eso no significa renunciar a las
propias metas-prácticas, pero siempre es necesario tener en cuenta los
niveles de fundamentación de mi propio actuar en el mundo. El actuar
práctico no se opone necesariamente al actuar ético, pero a veces entran
en conflicto. El punto es adecuar el actuar práctico al actuar ético, y
a largo plazo, que ni siquiera sea preciso adecuar uno al otro. Y sin
embargo, esta coincidencia entre el actuar práctico y el actuar ético es
una meta infinita, irrealizable por principio, a la que solo puedo
aspirar a acercarme asintóticamente.

¿Qué debo desear respecto al otro? Volverme yo mismo "medio" para que
pueda realizar una vida buena, para que pueda acceder a bienes
auténticos. Que yo, como finalidad para él, para ella, le permita
acceder a bienes, valores, verdaderos, auténticos. Dice Husserl:

#+BEGIN_QUOTE
  El mejor ser y el mejor querer y obrar posibles del otro forman parte
  de mi propio ser y querer y obrar, y a la inversa. Desear la bondad no
  sólo para mí, sino para toda la comunidad como comunidad de hombres de
  bien, y tener que incorporar esta empresa al círculo de mis fines
  prácticos, de mi voluntad práctica: todo ello pertenece a mi vivir
  auténticamente humano.
#+END_QUOTE

Ser verdaderamente hombre significa querer formar parte de una comunidad
verdaderamente humana, en donde todos aspiren a bienes infinitos. Esto
es: ser verdaderamente hombre implica querer realizar la Revolución, y
querer ser parte de la sociedad post-Revolucionaria, o revolucionaria,
dada que en última instancia, una comunidad post-capitalista sería una
comunidad en renovación constante, que realizaría un acrecentamiento
constante de los bienes auténticos a los que es capaz de acceder y los
que es capaz de realizar.

#+BEGIN_QUOTE
  Ser hombre verdadero es querer ser hombre verdadero e implica querer
  ser miembro de una humanidad «verdadera»; querer que, en la medida de
  lo prácticamente posible, mi comunidad de pertenencia sea una
  comunidad verdadera.
#+END_QUOTE

Le falta el momento "troskista" del deseo de la "revolución permanente"
a Husserl, pero está bien. Primero deseo que mi Umwelt sea una comunidad
verdadera (el "partido" diría Lenin, si hubiera dicho bien las cosas).
Luego, el horizonte entero del mundo tiene que ser mi proyecto. Del
mundo-infinito, por así decirlo: no solo de mis contemporáneos, sino de
todos los hombres, de todas las mónadas del futuro.

Hay que distinguir, sin embargo, entre el polo-ideal y las comunidades
posibles reales. Dice Husserl:

#+BEGIN_QUOTE
  Con todo, una determinada comunidad es una pluralidad de seres humanos
  que se guían por motivos en parte egoístas, en parte altruistas, y
  mayormente pasivos. De entre estos hombres, algunos se autodisciplinan
  a sí mismos, ponen en práctica la libre reflexión, la libre decisión;
  y algunos de entre ellos tienen además una voluntad de vida moral o,
  cuando menos, una actitud ética hacia la vida, una inclinación a
  comportarse éticamente (que no es la decisión firme, efectiva, de la
  voluntad que se dirige a una vida verdaderamente buena).
#+END_QUOTE

También están los "perversos", the unethical men diría Graffigna. Como
sea, de esta forma hasta cierto punto irreflexiva se van organizando y
constituyendo las comunidades, con sus metas buenas y malas, con sus
bienes buenos y malos, etc., etc. Tenemos en las sociedades realmente
existentes, /una mixtura de lo valioso y lo carente de valor, de lo que
un día acaso fue útil o respondió a un sentido axiológico más alto y hoy
es un vestigio devaluado que estorba a una obra de mayor valor/. En este
mundo están los hombres auténticamente hombres, que despertaron a la
vida-ética, y aquellos que no. Y es en este mundo que comienza nuestra
reflexión, y nuestras preguntas respecto a la *Renovación*. (Y también
los tiempos de toda renovación posible, recordemos el caracol en el IX
de Pentáculos: no precipitarse, como decía Descartes, tenacidad y
paciencia).

El hombre particular solo puede alcanzar bienes auténticos muy
limitados. Quien puede alcanzar una multiplicidad de tales bienes es la
comunidad. Por eso el hombre auténticamente bueno debe intentar, con los
medios a su alcance, despertar a la comunidad intersubjetiva a los
valores más altos de la humanidad. (Pero esto es dificil, cuando no
podemos despertar tales valores ni siquiera en individuos particulares,
completamente cercanos, próximos, de nuestro Umwelt inmediato). Solo de
esa forma podemos darle un sentido moral más alto a nuestras buenas
disposiciones innatas (o disposiciones como logros inalienables de la
reflexión sobre la propia vida, y la vida auténticamente buena).

La reflexión de Husserl continúa por estos puntos:

-  La eticidad de la comunidad se funda sobre los sujetos de distinto
   nivel ético.
-  Tanto el hombre individual como la comunidad pueden tener
   auto-conciencia, y el deseo de autoconfigurarse hacia niveles
   superiores de eticidad.
-  Para lo anterior es condición que las reflexiones éticas de los
   individuos, tanto respecto de sus propias vidas como respecto de su
   comunidad, se socialicen, se propagen en un "movimiento social".
-  Los conceptos /a priori/ para un trabajo científico que se proponga
   establecer los principios pertinentes a lo anterior son conceptos
   /válidos a priori/ respecto a la idea de ser humano y la idea de
   comunidad de seres humanos, y son tales como: mundo circundante
   individual, mundo circundante colectivo, mundo circundante físico y
   orgánico, animal y, por fin, mundo circundante del hombre.
-  También tenemos las figuras formalmente posibles de colectividades,
   como: matrimonio, amistad; pueblo, Iglesia, Estado, etc., con sus
   respectivas ideas normativas.
-  Para toda *renovación* es necesario que la conciencia moral
   individual haya despertado, y haya reflexionado tanto en lo que
   respecta a sus propias metas, como a las metas de la/s comunidad/es
   en la que vive.
-  Todo esto es asunto de una ciencia para Husserl, de la /ética
   científica/, que es una y abarca a la vez la vida individual y la
   vida social.
-  Pero la propia ciencia es un logro o una empresa colectiva. Toda
   ciencia se haya en referencia a sí misma, y a la comunidad en la cual
   se desarrolla. Se halla, por lo tanto, bajo el imperativo categórico
   de esta.
-  Por la anterior circunstancia, la ciencia ética puede verse requerida
   acerca de si /ella misma es un medio que necesariamente tiene que
   desarrollarse en una colectividad a fin de que ésta pueda escalar
   estadios axiológicos por principio más altos; y cuando se vea ante el
   requerimiento ulterior de en qué medida la ciencia, la ciencia
   universal, la filosofía, tiene necesariamente que haberse
   desarrollado en una colectividad a fin de que ésta alcance la forma
   de una colectividad éticapersonal, de una que conscientemente se ha
   configurado de acuerdo con la idea ética y que puede emprender el
   camino a un desarrollo deliberadamente más alto/.
-  La ciencia ética puede ser necesaria en dos sentidos: para configurar
   sus metas, para transitar hacia metas más altas.
-  Una comunidad despierta a la /humanitas/ si, primeramente, algunos
   hombres particulares han despertado a ella y logran transformar sus
   principios en posibilidades prácticas para la comunidad.
-  También puede acontecer que una "mónada-despierta-éticamente"
   mediante la predicación moral o la instrucción ética gane individuos
   para su causa, lo que puede poner en marcha un movimiento espiritual
   que eventualmente lleve a la renovación total de la comunidad (o sea:
   religión). Husserl lo llama la "/versión espiritual del principio de
   Huyghens/" (el principio de la propagación de ondas).
-  Algunos individuos de este movimiento espiritual podrían ver el valor
   del conocimiento del mundo. Se trataría así de promover un interes
   teórico en función del interés moral. Esto permitiría la
   configuración de una "comunidad de sabios" o algo así, Husserl acá ya
   está delirando con las posibilidades del movimiento fenomenológico.
   No contempla, en absoluto, luchas de fuerzas, intereses, no hay una
   dimensión verdaderamente "política" en nada de lo que dice. [%3 *y
   pero esta sería la comunidad patagónica, ¿no? Nosotros (entre otros,
   espero) vendríamos a ser los despiertos éticamente que vienen a
   compartir la palabra de la revolución y la renovación. La comunidad
   patagónica vendría a ser un momento de ese proceso*]
-  Una comunidad no es un mero conjunto de individuos, sino una
   multiplicidad con /igual voluntad según ideales iguales, para
   constituirse ya como comunidad de voluntades, comunidad en el
   querer/. (Ej: la comunidad de los matemáticos es una comunidad de
   voluntades en este sentido, comunidad articulada horizontalmente y no
   verticalmente para Husserl, más allá de lo que ocurra después con las
   Academias, etc.).
-  Una comunidad ética es tal cuando se ha dotado de un "estamento"
   universal de *funcionarios de la idea* y les ha conferido una
   autoridad con vigencia (como los filósofos en la Antigüedad, el
   clero, etc.).
-  Ese propio estamento, como comunidad o sub-comunidad, encarna un
   reino específico de valores ideales objetivos.

A propósito de esto último, replicando el ideal del "rey filósofo" de
Platón, dice Husserl:

#+BEGIN_QUOTE
  La condición de posibilidad de que se constituya una auténtica
  comunidad racional radica en que, por sobre los individuos que
  filosofan, se haga realidad un estamento de filósofos y una
  constelación de bienes objetivos comunes; o sea, un sistema cultural
  llamado «filosofía» que esté en proceso objetivo de desarrollo. Los
  filósofos están llamados a ser los representantes del espíritu de la
  razón, el órgano espiritual por el que la colectividad accede
  originaria y duraderamente a la conciencia de su verdadero destino (de
  su verdadera identidad) y el órgano cuya vocación es la propagación de
  esta conciencia en los círculos de «profanos». La filosofía misma es
  el depósito objetivo de su sabiduría y así el depósito de la sabiduría
  de la propia comunidad. En ella consta documentalmente la idea de la
  comunidad justa, o sea, la idea-meta que la propia comunidad se ha
  dado por medio de su estamento de filósofos, y que queda en esta
  figura objetiva a disposición permanente de los filósofos como órgano
  de la colectividad, con objeto de que sea actualizada y ejerza la
  influencia que le corresponde (o bien, queda a disposición de todo
  profano que, como miembro de la colectividad, quiera revivir para sí
  la comprensión de la idea). Igualmente, todo conocimiento del mundo
  que la filosofía objetiva, es en todo momento un medio dispuesto para
  el fin de hacer posible la intervención racional en el mundo
  circundante de una forma que sea racionalmente superior a la de la
  pericia práctica pre-filosófica. Por otra parte, sin embargo, la
  filosofía es un reino de valores ideales objetivos autónomos (valores
  absolutos). Cada creación de un valor ideal absoluto eleva el valor
  del hombre que lo gesta; y la actividad de gestarlo, considerada en y
  por sí misma, comporta una dimensión de vida absolutamente valiosa. Y
  comoquiera que todo bien de este orden es un bien común, lo mismo se
  aplica a la propia colectividad de la que el creador forma parte: como
  colectividad que rinde valores ideales absolutos, rinde algo
  absolutamente valioso y por tanto vive ya en la dimensión que requiere
  el fin de una humanidad más alta.
#+END_QUOTE

*** La forma axiológica superior de una humanidad propiamente humana.
    :PROPERTIES:
    :CUSTOM_ID: la-forma-axiológica-superior-de-una-humanidad-propiamente-humana.
    :END:

Husserl la define así:

#+BEGIN_QUOTE
  Se trata de la humanidad en que la filosofía como sabiduría sobre el
  mundo ha adoptado ya la figura de la filosofía como ciencia universal
  y ciencia estricta; de la humanidad en que la razón se ha cultivado y
  objetivado en la figura del logos.
#+END_QUOTE

Esto es: va a tratar de la forma correcta o "infinita" de la
/humanitas/. Se trata del desarrollo formal de la "utopia husserliana".

-  El mismo método de la *ciencia estricta* es el método que investiga
   las formas y normas del vivir humano. En esta investigación se basa
   el conocimiento de las *posibilidades prácticas* más altas para el
   hombre, y los ideales a los que debe apuntar como su meta.
-  La comunidad de los científicos anteriormente mentada, articula el
   saber como ciencia "técnica", y así la comunidad conoce y configura
   su estructura más auténtica, tanto estática como dinámicamente.
-  La ciencia misma solo existe en devenir. Por lo mismo la /humanitas/
   estará en constante renovación ('revolución permanente /a la/ Trotsky
   casi').
-  Alcanzado el /logos/, lo único que queda es un acrecentamiento
   constante. Dice Husserl: /En cada estadio tiene aún ante sí
   horizontes abiertos, indeterminaciones pendientes de determinarse/.
-  Se trataría de una comunidad *absolutamente racional*, cuya evidencia
   descansa en el trabajo científico de los fenomónologos como
   "científicos estrictos", como encarnaciones de la *razón lógica*. La
   sociedad no determina su trabajo, sino que su trabajo determina a la
   comunidad, que se deja guiar en un sentido *técnico-práctico*.
-  La técnica de que aquí se trata es, con todo, la técnica «ética», la
   técnica de autorrealización de la humanidad auténtica. Una 'tecnica'
   que da sus verdaderas normas a todo lo humano, a lo individual y a lo
   colectivo.
-  La ciencia (filosofía) investiga tanto las posibilidades culturales,
   sociales, etc; como en referencia retrospectiva a sus propias
   posibilidades de esencia y a las condiciones regladas de su
   posibilidad. Este rol solo puede desempeñarlo la ciencia estricta, y
   no el arte (contra Schiller).
-  La ciencia conoce el todo "de las realidades" mediante leyes fácticas
   y leyes de esencia. Toda utilidad que se derive tal conocimiento (por
   ej: la posibilidad de intervención "práctica" en la naturaleza
   física) se subordina a normas éticas.
-  Husserl se pregunta si estas reflexiones han de llevar a la creación
   de una "colectividad imperial", en donde una voluntad centralizadora
   -con el poder de mandar- decide los límites de una libertad dada a
   los individuos en tales o cuales esferas.
-  Husserl no responde a la pregunta de si el Imperio o el Estado es la
   forma apropiada para una comunidad ética, pero deja planteado el
   interrogante. También la pregunta respecto a los límites que tal
   Estado impondría a cada uno de los dominios de la cultura (si el arte
   estará subordinado a una norma estatal, o tan solo a la norma de la
   filosofía, etc).\\
-  Lo único cierto es que la forma Imperial, Estatal, etc., debe ser tal
   que deje que la comunidad desarrolle sus posibilidades, y por lo
   tanto, debe ser tal que permita variar las normas propias que en cada
   momento definen el /telos/ de las diferentes partes de la comunidad.
   [%4 \_\_Casi lo mismo que decía San Martín... ¿no?]
-  Respecto a esta problemática, Husserl dice que ha de explorarse hasta
   que punto una tradición "venerable", un mundo histórico (como
   horizonte de sentido) ha de ser considerado una herencia admisible,
   deseable, necesaria, incorporable, etc.

** V TIPOS FORMALES DE CULTURA EN LA EVOLUCIÓN DE LA HUMANIDAD
   :PROPERTIES:
   :CUSTOM_ID: v-tipos-formales-de-cultura-en-la-evolución-de-la-humanidad
   :END:

*** 1. El estadio de la cultura religiosa
    :PROPERTIES:
    :CUSTOM_ID: el-estadio-de-la-cultura-religiosa
    :END:

**** A. La religión «natural»
     :PROPERTIES:
     :CUSTOM_ID: a.-la-religión-natural
     :END:

1. "El animal vive bajo meros instintos, el hombre también bajo normas".
   Estas normas, sin embargo, pueden ser de naturaleza muy variada:
   pueden ser cc como leyes fácticas en vigencia, "arbitrariamente
   establecidas por quienes de manera contingente ejercen el poder";
   resultado de una tradición inauténtica en condiciones contingentes.
   Pero también pueden ser cc como normas de /vigencia absoulta/,
   imperativos incondicionales, categóricos. Husserl da como ejemplo de
   esto último los mandatos divinos, en tanto que se dan a la conciencia
   como absolutos, no porque sean auténticos. Es decir, los mandatos
   divinos se viven como absolutos e incondicionales, a diferencia de
   las leyes de un país o época, que cambian contingentemente, y uno es
   cc de eso.
2. "En toda cultura altamente desarrollada, o respectivamente en toda
   humanidad que se muestra activa en múltiples y diversas formas
   culturales, a través de las cuales se va configurando, hallamos una
   forma cultural señalada: la «religión»". La religión es el estadio
   superior de la cultura mítica, en el que los seres trascendentes de
   absolutizan y convierten en dispensadores de normas y valores
   absolutos, valores q son revelados y en cuyo cumplimiento radica la
   salvación.

Esta forma de cultura religiosa se encuentra entre las más antiguas
formas de cultura altamente desarrollada. Ya la cultura babilonia
contaba con la noción de /civitas dei/. Se caracteriza por la ordenación
de toda la vida según dichas normas, en todos los niveles y aspectos. Lo
que H. entiende como vida ética auténtica, está dado en la cultura
relgiosa por los valores religiosos absolutos:

#+BEGIN_QUOTE
  "en el sacerdocio, una idea-meta constituida conscientemente, y está
  viva una voluntad que se ordena a ella como a su fin; voluntad ésta
  que de manera mediata pertenece a toda [69] la comunidad y se sostiene
  en toda la comunidad que participa de ella. Tal idea-meta es la de una
  regulación universal y absoluta de toda la cultura bajo el sistema de
  normas absolutas que hay que derivar de la revelación divina"
#+END_QUOTE

**** B. El movimiento de libertad religiosa como figura histórica
     :PROPERTIES:
     :CUSTOM_ID: b.-el-movimiento-de-libertad-religiosa-como-figura-histórica
     :END:

Las culturas teocráticas tienen la 'virtud' de tener cc de finalidad, de
ordenar la vida entera según normas y de producir regocijo en su
cumplimiento. Sin embargo, tienen el carácter de la falta de libertad.
La fe es heredada y repetida, "/Libertad/ es, en cambio, una expresión
para la facultad y sobre todo para el hábito adquirido de tomar una
postura crítica a propósito de lo que, primeramente sin reflexión, se da
a la conciencia como verdadero, como valioso, como debiendo ser en
sentido práctico. Toma de postura crítica que es el fundamento de la
decisión libre que tiene lugar a continuación".

La libertad puede desarrollarse según: 1) la figura de un movimiento de
libertad religiosa; 2) la figura del desarrollo de la ciencia libre, que
primero discurre independientemente de la religión y luego libera al
conocimiento de sus ataduras.

#+BEGIN_QUOTE
  "Filosofía y ciencia en libertad, como función de la razón teórica
  autónoma, se desarrollan en la nación griega, y en un movimiento
  progresivo determinan la evolución de un espíritu general de vida
  cultural libre a partir de la razón autónoma. Este espíritu se
  extiende triunfalmente más allá de la nación griega y da lugar a la
  unidad de una cultura helénica y, con ella, a lo específicamente
  europeo".
#+END_QUOTE

**** C. La figura de la cultura religiosa medieval
     :PROPERTIES:
     :CUSTOM_ID: c.-la-figura-de-la-cultura-religiosa-medieval
     :END:

La edad media nace entonces de ambos movimientos, del espíritu
filosófico-científico libre de los griegos y de la expansión universal
cristiana. Es el intento de congeniar la racionalidad intuitiva de la fe
y la de la filosofía, la libertad del cristiano y la del filósofo. Así,
la 'nueva religión' no puede evitar desarrollar una teología, entendida
como la articulación intelectual de los contenidos de la fe.

Sin embargo, el resultado de este movimiento llegó a un dogmatismo
tradicionalista:

#+BEGIN_QUOTE
  "Así, el hecho de que el proceso de dogmatización, de absolutización
  teológica de las interpretaciones filosóficas de unos contenidos que
  eran originariamente intuitivos, provocase un tradicionalismo que no
  sólo frenó la libertad de interpretación racional conforme a nuevas
  evidencias filosóficas, sino que también apartó la vida religiosa del
  creyente de sus fuentes intuitivas originarias; que llevó incluso a la
  separación entre ambas y a la sustitución de la dicha que brota de la
  intuición por la satisfacción producto de una corrección extrínseca de
  la fe al aceptar fórmulas que no comprende".
#+END_QUOTE

De esta tensión entre fe y filosofía proviene entonces la disolución del
espíritu medieval, que pierde su fuerza de desarrollo cultural.

*** 2. El estadio de la cultura científica
    :PROPERTIES:
    :CUSTOM_ID: el-estadio-de-la-cultura-científica
    :END:

**** A. La figura del movimiento de libertad filosófica. La esencia de
la ciencia auténtica
     :PROPERTIES:
     :CUSTOM_ID: a.-la-figura-del-movimiento-de-libertad-filosófica.-la-esencia-de-la-ciencia-auténtica
     :END:

Lo cito a Husserl siendo políticamente incorrecto para nuestros
estándares posmo:

#+BEGIN_QUOTE
  "[...] la humanidad que despliega su vitalidad en la cultura europea y
  la propia vida que discurre en el seno de esta cultura tienen una
  forma especial merecedora de la más alta valoración axiológica; una
  forma en cuya virtud esta humanidad escala la altura máxima que le es
  exigible como humanidad en general: el nivel de una humanidad que en
  su cultura se configura a sí misma y configura su mundo circundante
  desde la pura razón autónoma y, en particular, desde la razón
  científica. [...] que nosotros estimamos la cultura europea ---cuyo
  tipo de desarrollo hemos así descrito--- no sólo como la que goza de
  la posición relativamente más alta entre todas las culturas de la
  Historia, gracias a haber realizado su tipo de desarrollo, sino que
  vemos en ella la primera realización de una norma absoluta de
  desarrollo que está llamada a revolucionar cualquier otra cultura en
  proceso de desarrollo"
#+END_QUOTE

A partir del concepto fuerte de /creencia/ o /juicio/ entendido como
proposición con contenido y modo, que permaence idéntico a través del
tiempo, que repite la misma creencia en diferentes actos temporales y se
va estableciendo como tal, como creencia firmemente creída, surge la "la
«ciencia» como sistema de bienes en común y como bien común que es
unitario gracias a su sistematización". La "solidez intersubjetiva" y la
objetivdad de la ciencia descansan en el hecho de que las creencias se
mantienen firmes como bienes comunes, que no cambian de momento a
momento según las circunstancias.

La ciencia se compone de juicios 'entera o absolutamente ciertos',
aquellos que se extraen a partir de fundamentaciones hasta retrotraerse
a certezas últimas; y juicios 'evidentes', aquellos que se experimentan
en persona y cuya evidencia es vivida por uno mismo al formularlos. De
aquí se sigue entonces que, contra Horacio y sus indios, Quine y su no
se qué de la traducción, que:

#+BEGIN_QUOTE
  "Por sobre todas las diferencias entre individuos, entre naciones,
  entre tradiciones en vigor y firmemente arraigadas, se [85] encuentra
  «lo que es común a todos» y que responde al título de un «mundo común
  de cosas» que se constituye en experiencias intercambiables, de modo
  que todos pueden entenderse con todos, todos recurrir a una identidad
  que está a la vista. Y, en referencia primera a ello y después
  trascendiéndolo, se abre un reino de la verdad que cada hombre puede
  poner ante su mirada, que cada uno, intuyendo, puede realizar en sí
  mismo, cualquiera que sea su círculo cultural de procedencia, amigo o
  enemigo, griego o bárbaro, hijo del pueblo de Dios o hijo de pueblos
  hostiles a Dios"
#+END_QUOTE

La filosofía o ciencia auténtica surge entonces del adoptar la actitud
teorética que trasciende las determianciones circunstanciales y
encuentra el gozo en el conocimiento, como vocación.

**** B. La formación de la cultura filosófica en Grecia. Los dos
estadios de la auténtica ciencia
     :PROPERTIES:
     :CUSTOM_ID: b.-la-formación-de-la-cultura-filosófica-en-grecia.-los-dos-estadios-de-la-auténtica-ciencia
     :END:

El estadio de ciencia pre-auténtica se encuentra entre los griegos, en
quienes despierta la filosofía por el interés por dar cuenta del
Universo, sus enigmas y principios universales. No llega a ser ciencia
auténtica, dice Husserl, porque le falta el momento de la reflexión
'logica' o 'gnoseológica':

#+BEGIN_QUOTE
  "Tras la filosofía ingenua del período-estadio previo, la filosofía y
  la ciencia propiamente tales empiezan con las reflexiones socráticas y
  platónicas acerca del método, y la «dialéctica» platónica es el primer
  y fundamental fragmento de una ciencia de la esencia de la ciencia, de
  una doctrina de la ciencia. Y en lo sucesivo, una lógica como
  disciplina del método de conocimiento verdadero y de la ciencia
  formará ya parte de toda filosofía de la posteridad"
#+END_QUOTE

#+BEGIN_QUOTE
  "La gloria eterna de la nación griega no es sólo haber fundado la
  filosofía en general como una figura cultural que responde a un
  interés puramente teórico, sino el que su doble constelación estelar
  Sócrates-Platón haya llevado a término la creación única de la idea de
  la ciencia lógica y de la lógica como doctrina universal de la
  ciencia, como ciencia normativa central de la ciencia en general. La
  noción de logos como razón autónoma, en primer término como razón
  teórica, como facul-[92]-tad de juzgar «en completo desprendimiento de
  uno mismo», como juzgar que en pura evidencia escucha exclusivamente
  la voz de las cosas mismas, recibe así su articulación conceptual
  originaria, y con ella, a la vez, su fuerza transformadora del mundo.
  Y no menos la idea de la lógica, de la ciencia de la razón como
  organon de toda ciencia auténtica"
#+END_QUOTE

La ciencia consiste entonces en la adquisición de verdades y también en
su comunicación y transmisión. Todos gozan de las verdades producidas y
sobre ellas adquieren nuevas y nuevas. Sobre los valores del
conocimiento se fundan, entonces, nuevos valores, valores 'éticos',
personales y de comunidad.

La filosofía es primero puramente teórica y luego se vuelve práctica.
Sigo citando in extenso porque me pinta más claro que mi paráfrasis:

#+BEGIN_QUOTE
  "La ciencia, la filosofía, es en un principio, aunque no por mucho
  tiempo, cosa «nada práctica»; obra pura de intereses teóricos
  intersubjetivamente socializados, reino objetivo de bienes por cuya
  utilidad extrateórica no se pregunta y que en su origen tampoco es
  motivo de apreciaciones de utilidad ni de producciones útiles. Los
  problemas cosmológicos y las teorías cosmológicas, que con su vasta
  generalidad y primitiva vaguedad dominaron inicialmente el interés, se
  movían, en efecto, a unas alturas abstractas que dejaban muy atrás
  todos los dominios de la praxis humana, de modo que también se
  mantenía apartado todo pensamiento relativo a un posible
  aprovechamiento práctico"
#+END_QUOTE

Y se vuelve práctica:

#+BEGIN_QUOTE
  "El volver la atención de la filosofía hacia la praxis, o sea, la
  inclusión de ésta en el interés teórico, señala en perspectiva
  histórica el punto más significativo del desarrollo de la filosofía,
  en la medida en que sólo este giro motivó la fundamentación de la
  lógica y de la filosofía bajo norma lógica. Mas no sólo eso. La
  fundamentación de una filosofía universal que abarque el ser y el
  deber ser, los hechos y las normas, halló aquí igualmente su punto de
  partida, como también la creación de la idea [95] de la vida
  filosófica, de una vida verdaderamente humana como vida en la razón
  filosófica"
#+END_QUOTE

**** C. La evolución de la figura de la cultura filosófica en la Edad
Media y en la Modernidad Ahora
     :PROPERTIES:
     :CUSTOM_ID: c.-la-evolución-de-la-figura-de-la-cultura-filosófica-en-la-edad-media-y-en-la-modernidad-ahora
     :END:

El espíritu griego era uno de cultura humana en libertad, de
/humanitas/, una vida cultural auténtica en la libre razón filosófica.
Los filósofos eran "los representantes del principio normativo rector de
la razón libre". Esto deja paso al espíritu medieval, donde se pierde la
libertad, los filósofos son reemplazados por los sacerdotes. "Si la
comunidad de filósofos había sido, por así decirlo, «comunista» y su
idea directriz no se sustentaba en una voluntad que abarcase al
colectivo social, ahora la comunidad correspondiente, la de los
sacerdotes, es «imperialista» y está dominada por una voluntad
unitaria." Aguante los filósofos comunistas.

Sin embargo, el cambio no es disruptivo, sino que existe una plena
continuidad entre el espíritu griego y el medieval, dado que la
filosofía griega sige actuando como formadora de la vida espiritual,
incluso para la religión cristiana. Así el "renacimiento", más allá de
sus peculiaridades históricas, es el renacimiento del espíritu
libre-filosófico de los griegos y es el renacimiento de la idea-meta de
Humanidad.

La modernidad:

1. "La Modernidad como irrupción de una actitud general de toma
   autorresponsable de postura a propósito de todas las convicciones
   teóricas y prácticas previamente dadas; como movimiento, pues, de
   libertad y en particular movimiento de libertad filosófica, es decir,
   como renacimiento de la vida cultural antigua en el sentido de un
   vivir racional de una colectividad humana a partir de la razón
   filosófica (ciencia); y también como movimiento de libertad
   religiosa, es decir, como renacimiento del ideal religioso cristiano
   primitivo (o del que se tenía por cristiano primitivo) de una
   religión a partir de la experiencia religiosa originaria, de las
   fuentes originarias de la fe. Ambos movimientos, unidos amistosamente
   en el primer momento, van por fuerza separándose. [...] Para la
   filosofía, en cambio, la fe es en el mejor de los casos una de las
   fuentes cognoscitivas y se somete, como todas las fuentes de
   conocimiento, a la crítica libre. La filosofía es absolutamente
   independiente, la «razón» es principio normativo de la propia fe y de
   los límites de su derecho".
2. "Esta actitud «moderna» hacia la fe no significa rechazo de la fe
   como experiencia religiosa, como tampoco rechazo de los contenidos
   esenciales de la fe. Significa una pretensión de libertad para decir
   sí o decir no a la fe, y por tanto una libertad de decidir en favor
   del ateísmo".
3. "La Modernidad se diferencia por el modo en que la filosofía o la
   ciencia representan en la Antigüedad la autonomía de la razón como
   fuente de toda autoridad y de toda validez o vigencia, y ello sobre
   la base de la diferencia entre ciencia antigua y ciencia moderna.
   [...] encuentra una única ciencia particular que ya en la Antigüedad
   había al-[102]-canzado reconocimiento general y que no se había visto
   enredada en los conflictos de las filosofías, ni envuelta en diversos
   sistemas con planteamientos diversos y contradictorios, a saber: la
   matemática".
4. "Idea de la justificación absoluta. Crítica de la razón".
5. "La idea práctica de una cultura universal a partir de la razón".

FIN.

[1] Lo dejó acá porque sino voy a comentar el texto de 1923 entero y no
    da, pero anote las ideas que a Ud. le parezcan pertinentes tener a
    mano.

[2] Por /personalidad/ en Ideen II entiende el /sujeto empírico/ créo,
    el problema es entender qué entiende por /tipos de personalidades
    humanas/; pero también, siguiendo a Ideen II, creo que usa la
    expresión como entendiendo una doctrina (Lehre) de los
    temperamentos, carácteres, etc, etc.

[3] M: ¿Si es inevitable sigue siendo mera 'posibilidad'?, E: Sí, en el
    sentido en que /necesidad/ y /posibilidad/ no se contradicen entre
    sí; toda necesidad tiene que ser, previamente, una posibilidad.
